version: '3.1'

services:
  vcIssuance:
    build:
      context: './vcIssuance'
      dockerfile: Dockerfile
    image: 'vc-issuance-trussihealth:latest'
    ports:
      - 3000:3000
    env_file:
      - './vcIssuance/.env'
  eSeal:
    build:
      context: './eSeal'
      dockerfile: Dockerfile
    image: 'eseal-trussihealth:latest'
    ports:
      - 3001:3001
    env_file:
      - './eSeal/.env'
